### ISSUE TITLE
Request for the release for Windows 

### ISSUE THREAD

**Issue by KaiyueZou** [neurolabusc/nii2mesh#10]
Thank you for the fantastic work! The solutions for compiling are comprehensive and informative; however, it would be very helpful if the compiled version of the program for Windows could be found in the [release](https://github.com/neurolabusc/nii2mesh/releases). Thanks a lot!

**Comment by neurolabusc** [comment]
You can get a pre-compiled version of [niimath](https://github.com/rordenlab/niimath/releases). Niimath is a superset of fslmaths, nii2mesh and other features. There is nothing that nii2mesh can do that you can not do with niimath. The idea of the nii2mesh repository is to provide a minimal solution that allows other developers to re-use the code. For individuals seeking a compiled executable, niimath is the way to go.
