### ISSUE TITLE
Incorrect orientation of exported meshes

### ISSUE THREAD

**Issue by thangngoc89** [neurolabusc/nii2mesh#11]
Hey, thank you for making and publishing nii2mesh. I'm a big fan of your works (using NiiVue for open visualization).
I've notice that the generated meshes from nii2mesh is in a different orientation comparing to the voxel orientation. I need to perform a *180 degrees rotation around the Z axis in local coordinates of the object** for correction.

I've tested and confirmed with different files having these original affine: RAS, LPS and LAI.

Example file:

1. I created a rough segmentation using 3D Slicer for `bet.nii.gz` provided on `nii2meshweb` demo.
You could download it here [bet.seg.nii.gz](https://github.com/neurolabusc/nii2mesh/files/15261690/bet.seg.nii.gz)
2. Run `nii2mesh`:

```sh
nii2mesh bet.seg.nii.gz -a 1 bet_.ply
```

Output [bet_1.ply.zip](https://github.com/neurolabusc/nii2mesh/files/15261709/bet_1.ply.zip)

3. View with 3D Slicer:

Green is segmentaiton visualization, yellow is model:

<img width="640" alt="image" src="https://github.com/neurolabusc/nii2mesh/assets/3049054/b04b588b-0d2b-4a63-a819-c31292147fe2">
<img width="700" alt="image" src="https://github.com/neurolabusc/nii2mesh/assets/3049054/d1de74b0-e652-4382-bece-4f0c1414b8a4">

Happy to provide any more details that you need.

**Comment by neurolabusc** [comment]
This reflects the fact that [DICOM uses LPS while NIfTI uses the RAS coordinate system](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Spatial_Coordinates). This tool (as well as Surfice and NiiVue) uses RAS [Talairach_coordinates](https://en.wikipedia.org/wiki/Talairach_coordinates) popular in neuroimaging (e.g. NIfTI, GIfTI, TRX, etc), whereas Slicer3D defaults to LPS.

To demonstrate the behavior, convert the [AIL.nii.gz](https://github.com/niivue/niivue/tree/cb8612d300ff59585eb48cfe7b2b2fbd68dbc940/demos/images) image, where the columns, rows and slices are saved to disk as posterior->anterior, superior->inferior, and right->left respectively (alternatively, try any of the [48 combinations](https://github.com/rordenlab/NIfTIspace)) using nii2mesh. Drag and drop the resulting obj mesh onto the [NiiVue worldspace demo](https://niivue.github.io/niivue/features/worldspace2.html) and click the `cube` checkbox to show the spatial directions. Note that the orientation of the voxels is preserved in the image:

![AIL](https://github.com/neurolabusc/nii2mesh/assets/8930807/00855f04-56d3-4e54-914b-2062ea12d84c)

You can further investigate the polarity by leveraging the fact that the OBJ format is a text format, and you can edit the first line of the text file to change the spatial position of the first vertex, which is initially 
```
v 72.2707 -36.1367 -0.389995
```
Doing so, you can see that NiiVue interprets the first component as ascending rightwards, the second component as ascending anteriorly, and the third component as ascending superiorly. Therefore, the mesh uses the same [RAS coordinate system](https://brainder.org/2012/09/23/the-nifti-file-format/).

To resolve the issue, choose use the `Show options` button with Slicer3D and set the `Coordinate system` to `RAS`:

![ras](https://github.com/neurolabusc/nii2mesh/assets/8930807/b76b93ee-a402-4c5e-95bf-bdab0cfa00de)

**Comment by thangngoc89** [comment]
Thank you for a very detailed explanation. As I understand it, nii2mesh exports meshes to RAS coordinate regardless of the input coordinate system. Is that correct? Given that the meshes don't carry coordinate or affine information, it would be up to downstream users to ensure the correct coordinate system.

**Comment by neurolabusc** [comment]
Yes. To clarify: nii2mesh reads NIfTI images which uses the RAS coordinate system. The [NIfTI header orientation information](https://brainder.org/2012/09/23/the-nifti-file-format/) is used to transform the voxels to vertices specified with RAS coordinates, regardless of the order that voxels are saved to disk.

**Comment by thangngoc89** [comment]
> nii2mesh reads NIfTI images which uses the RAS coordinate system

I totally understand this part.

The reason I said this:

> nii2mesh exports meshes to RAS coordinate regardless of the input coordinate system

is because that my input NIfTI file has LPS orientation (converted from DICOM using SimpleITK). 

The LPS orientation is confirmed with nibabel:

```python
import nibabel as nib
img = nib.load(nii_file)
print(nib.aff2axcodes(img.affine))
# ("L", "P", "S")
```

So is it safe to assume that `nii2mesh` ALWAYS return the mesh in RAS coordinate system regardless of the input coordinate system?

**Comment by neurolabusc** [comment]
Yes. The nii2mesh mesh vertices are always RAS, regardless of the order that input voxels are stored to disk.

Note that NIfTI always describes world space as RAS, and there are logically 48 [combinations that data can be stored to disk](https://github.com/rordenlab/NIfTIspace). The NIfTI header spatial transformation(s) map voxel to world space. One little wrinkle is that the NIfTI header can store two independent spatial transforms: the quaternion-based QForm and the matrix-based SForm. Similar to most tools, when both are specified my tools give precedence to the SForm. However, be aware that at least historically VTK tools gave precedence to the QForm. I believe this was because those tools could not store the shear of rhomboidal volumes (the SForm has 12 degrees of freedom while the QForm has 9).

**Comment by thangngoc89** [comment]
Thank you so much and have a good day.
