### ISSUE TITLE
Scope of functions defined in quadric.c

### ISSUE THREAD

**Issue by gllmflndn** [neurolabusc/nii2mesh#7]
Would it be OK to add a `static` keyword to all functions in `quadric.c` apart from `quadric_simplify_mesh`, `laplacian_smoothHC` and `laplacian_smooth` (and perhaps expose `laplacian_smooth` in `quadric.h`)?

It also seems that `time.h` does not need to be included.

**Comment by neurolabusc** [comment]
@gllmflndn please close if the latest commit resolves this issue.

**Comment by gllmflndn** [comment]
Thanks! Is there a reason why `symMatDet` and `vCross` in `quadric.c` were not included to have a `static` keyword?

**Comment by neurolabusc** [comment]
Sorry, missed those. Do you know an easy way to report all the global functions in C code?

**Comment by neurolabusc** [comment]
To answer my own question, compile with `-Wmissing-prototypes`

**Comment by gllmflndn** [comment]
Thanks again! I didn't know about `-Wmissing-prototypes` - it might come in handy. The `static` keyword matters to me because of an odd bug I observed with the `-Bsymbolic-functions` compilation flag with Octave ([bug #55363](https://savannah.gnu.org/bugs/?55363)).
