### ISSUE TITLE
Missing releases

### ISSUE THREAD

**Issue by olinickalls** [neurolabusc/nii2mesh#8]
Hi-

  Would it be possible to upload a release for windows please?  The readme alludes and even links to one, but no release seems to be present.

 I have tried compiling myself (although admittedly I can only get the 'cl' compile to run.) - it appears to compile without error, but whenever I execute from the cmd line the program does not seem to create an output file.  Perhaps this is the compatibility issue described in the readme.md

Cheers-
 Oli

**Comment by neurolabusc** [comment]
[nii2mesh](https://github.com/neurolabusc/nii2mesh) is a minimal demonstration program, really aimed at developers. Please see [niimath](https://github.com/rordenlab/niimath#converting-voxelwise-images-to-a-triangulated-mesh), which wraps these functions (and many others) into a highly optimized tool.

**Comment by olinickalls** [comment]
OK- Thanks- I'll check it out.
