### ISSUE TITLE
incomplete conversion

### ISSUE THREAD

**Issue by Zhang-JnQn** [neurolabusc/nii2mesh#9]
Only half of my tooth model is left after the conversion
![微信截图_20230426104702](https://user-images.githubusercontent.com/96648587/234453709-a3a748f3-5f82-4439-ae2b-ac0b3f2c2464.png)
The original nii.gz model contained both upper and lower teeth

**Comment by neurolabusc** [comment]
Extracting the largest object is the intended behavior, and is a feature not a bug. [Note that you](https://github.com/neurolabusc/nii2mesh#processing-steps) choose to only retain the largest connected object (`-l 1`) or keep all objects (`-l 0`).

**Comment by Zhang-JnQn** [comment]
Thanks.
